title: Foody Blog
author: Flora Cai
email: fcai@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This blog is for foods that I like!
theme: minima
# social links
twitter_username: alolafauna # DO NOT include the @ character, or else the build will fail!
github_username:  fcai254 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
